#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
y=$1
d=$2
D=$(printf "%02d" "$d")

"${SCRIPT_DIR}/gen-readme" "${y}" "${d}"
git add .
git ci -m "day${D} complete"
