#!/usr/bin/env bash
DIR=`dirname "$BASH_SOURCE"`
set -euo pipefail

source "${DIR}/../.env"

y=$1
d=$2
D=$(printf "%02d" "$d")

DEST=${DIR}/../${y}/days/${D}
mkdir -p "${DEST}"

# DEPS
# pup - https://github.com/ericchiang/pup
# html2md - https://github.com/suntong/html2md
tmpfile=$(mktemp)
trap EXIT `rm -rf $tmpfile`

url="https://adventofcode.com/${y}/day/${d}"

curl "$url" \
  -H "cookie: session=${SESSION_ID}" \
  | pup --pre --plain 'article' \
  | sed -e "s/---//g" \
  > $tmpfile

echo "<h2>Link</h2>" >> $tmpfile
echo "<a href='$url'>$url</a>" >> $tmpfile

cat $tmpfile | html2md -i > "${DEST}/README.md"

prettier --write "${DEST}/README.md"
