#!/usr/bin/env bash
DIR=`dirname "$BASH_SOURCE"`
set -euo pipefail

source "${DIR}/../.env"

y=$1
d=$2
D=$(printf "%02d" "$d")

DEST=${DIR}/../${y}/days/day${D}
mkdir -p $DEST

# DEPS
# pup - https://github.com/ericchiang/pup
# html-to-md - https://www.npmjs.com/package/html-to-md

# html-to-md needs some work
# it stops reading on \n when piping from curl
# but it seems to be fine when piping a file
#
# This block is from
# https://stackoverflow.com/questions/55435352/bad-file-descriptor-when-reading-from-fd-3-pointing-to-a-temp-file
# We're creating a temporary file that will delete itself when the program finishes
tmpfile=$(mktemp)
trap EXIT `rm -rf $tmpfile`

url="https://adventofcode.com/${y}/day/${d}"

curl "$url" \
  -H "cookie: session=${SESSION_ID}" \
  | pup --pre --plain 'article' \
  | sed -e "s/---//g" \
  > $tmpfile

echo "<h2>Link</h2>" >> $tmpfile
echo "<a href='$url'>$url</a>" >> $tmpfile

cat $tmpfile | html2md > "${DEST}/README.md"

prettier --write "${DEST}/README.md"
