#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/../.env"

y=$1
d=$2
D=$(printf "%02d" "$d")

DEST=${SCRIPT_DIR}/../${y}/days/${D}
mkdir -p "${DEST}"

# DEPS
# pup - https://github.com/ericchiang/pup
# html2md - https://github.com/suntong/html2md
tmpfile=$(mktemp)
trap EXIT $(rm -rf "${tmpfile}")

url="https://adventofcode.com/${y}/day/${d}"

curl "$url" \
  -H "cookie: session=${SESSION_ID}" \
  | pup --pre --plain 'article' \
  | sed -e "s/---//g" \
  > "$tmpfile"

echo "<h2>Link</h2>" >> "$tmpfile"
echo "<a href='$url'>$url</a>" >> "$tmpfile"

html2markdown --input "$tmpfile" --output "${DEST}/README.md" --output-overwrite

prettier --write "${DEST}/README.md"
