#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/../.env"

y=$1
d=$2
D=$(printf "%02d" "$d")

DEST=${SCRIPT_DIR}/../${y}/days/${D}
mkdir -p "${DEST}"

curl --progress-bar \
  "https://adventofcode.com/${y}/day/${d}/input" \
  -H "cookie: session=${SESSION_ID}" > "${DEST}/input.txt"
