#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

y=$1
d=$2
D=$(printf "%02d" "$d")

DEST="${SCRIPT_DIR}/../${y}/days/${D}"
mkdir -p "${DEST}"

"${SCRIPT_DIR}/get-input" "${y}" "${d}"
"${SCRIPT_DIR}/init-day-rust" "${y}" "${d}"
