#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

y=$1
d=$2
D=$(printf "%02d" "$d")

FILE="${SCRIPT_DIR}/../${y}/solution/rust/src/days/day${D}.rs"
MOD_FILE="${SCRIPT_DIR}/../${y}/solution/rust/src/days/mod.rs"
if test -f "${FILE}"; then
  echo "Day ${d} solution file already exists, aborting init"
  exit 1
fi
cp "${SCRIPT_DIR}/tpl/rust/dayXX.rs.tpl" "${FILE}"
perl -i -p0e "s/XX/${D}/g" "${FILE}"
perl -i -p0e "s/X/${d}/g" "${FILE}"
perl -i -p0e "s/(mod day[0-9]{2};\n)\n/\1mod day${D};\n\n/g" "${MOD_FILE}"
perl -i -p0e "s/; [0-9]+\]/; ${d}]/g" "${MOD_FILE}"
perl -i -p0e "s/(&day[0-9]{2}::Day[0-9]{2},)\n\]/\1\n    &day${D}::Day${D},\n\]/g" "${MOD_FILE}"
